--Exercise # 2 
--1) Write a program to fetch data from table SALES for a given orderid and display the data.

DECLARE
    VAR_SALES_DATE SALES.SALES_DATE%TYPE;
    VAR_ORDER_ID SALES.ORDER_ID%TYPE:= '1269';
    VAR_PRODUCT_ID SALES.PRODUCT_ID%TYPE;
    VAR_CUSTOMER_ID SALES.CUSTOMER_ID%TYPE;
    VAR_SALESPERSON_ID SALES.SALESPERSON_ID%TYPE;
    VAR_QUANTITY SALES.QUANTITY%TYPE;
    VAR_UNIT_PRICE SALES.UNIT_PRICE%TYPE;
    VAR_SALES_AMOUNT SALES.SALES_AMOUNT%TYPE;
    VAR_TAX_AMOUNT SALES.TAX_AMOUNT%TYPE;
    VAR_TOTAL_AMOUNT SALES.TOTAL_AMOUNT%TYPE;
BEGIN
    SELECT SALES_DATE, ORDER_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID, QUANTITY, UNIT_PRICE, SALES_AMOUNT, TAX_AMOUNT, TOTAL_AMOUNT
    INTO
    VAR_SALES_DATE, VAR_ORDER_ID, VAR_PRODUCT_ID, VAR_CUSTOMER_ID, VAR_SALESPERSON_ID, VAR_QUANTITY, VAR_UNIT_PRICE, VAR_SALES_AMOUNT, VAR_TAX_AMOUNT, VAR_TOTAL_AMOUNT
    FROM SALES 
    WHERE ORDER_ID = VAR_ORDER_ID;
    
    DBMS_OUTPUT.PUT_LINE(VAR_SALES_DATE|| ',' || VAR_ORDER_ID|| ',' || VAR_PRODUCT_ID|| ',' || VAR_CUSTOMER_ID|| ',' || VAR_SALESPERSON_ID|| ',' || VAR_QUANTITY|| ',' || VAR_UNIT_PRICE|| ',' || VAR_SALES_AMOUNT|| ',' || VAR_TAX_AMOUNT|| ',' || VAR_TOTAL_AMOUNT);
END;
/
--(Use %TYPE when declaring variables). 
--2) Write a program to insert data into SALES table. 

SELECT * FROM SALES;

DECLARE
    VAR_SALES_DATE SALES.SALES_DATE%TYPE := '11-11-2000';
    VAR_ORDER_ID SALES.ORDER_ID%TYPE:= '1111';
    VAR_PRODUCT_ID SALES.PRODUCT_ID%TYPE := '200';
    VAR_CUSTOMER_ID SALES.CUSTOMER_ID%TYPE := '11';
    VAR_SALESPERSON_ID SALES.SALESPERSON_ID%TYPE := 2000;
    VAR_QUANTITY SALES.QUANTITY%TYPE := 4;
    VAR_UNIT_PRICE SALES.UNIT_PRICE%TYPE := 30;
    VAR_SALES_AMOUNT SALES.SALES_AMOUNT%TYPE := 500;
    VAR_TAX_AMOUNT SALES.TAX_AMOUNT%TYPE := 5;
    VAR_TOTAL_AMOUNT SALES.TOTAL_AMOUNT%TYPE := 657;
BEGIN
    
    INSERT INTO SALES
    VALUES
    (VAR_SALES_DATE, VAR_ORDER_ID, VAR_PRODUCT_ID, VAR_CUSTOMER_ID, VAR_SALESPERSON_ID, VAR_QUANTITY, VAR_UNIT_PRICE, VAR_SALES_AMOUNT, VAR_TAX_AMOUNT, VAR_TOTAL_AMOUNT);
    
    commit;
    
    DBMS_OUTPUT.PUT_LINE('Data Inserted Successfully');

END;
/
SELECT * FROM SALES;

--3) Write a program to update data in SALES table for a given orderid (Change order 
--amount to 100).


DECLARE 
    VAR_ORDER_ID SALES.ORDER_ID%TYPE := '1111';
BEGIN
    UPDATE SALES
    SET sales_amount = 100
    WHERE ORDER_ID = VAR_ORDER_ID;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Updated Sales Amount to 100 for order id: ' || VAR_ORDER_ID  );

END;
/
SELECT * FROM SALES;


--4) Write a program to delete data from SALES table for a given orderid. 

DECLARE
    VAR_ORDER_ID SALES.ORDER_ID%TYPE := '1111';

BEGIN
    DELETE FROM SALES
    WHERE ORDER_ID = VAR_ORDER_ID;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Record deleted successfully for Order ID: ' || VAR_ORDER_ID);

END;
/

SELECT * FROM SALES;
